import os

OUTPUT_DIR = "clips"
LOGS_DIR = "logs"
TEMP_DIR = "temp"

TARGET_WIDTH = 1080
TARGET_HEIGHT = 1920
TARGET_ASPECT_RATIO = 9 / 16

MIN_SCENE_DURATION = 3
MIN_CLIP_DURATION = 15
MAX_CLIP_DURATION = 90
PREFERRED_CLIP_DURATION = 50

OUTPUT_BITRATE = "8000k"
OUTPUT_FPS = 30

SCENE_DETECTION_THRESHOLD = 27.0

MOTION_THRESHOLD = 5.0
MOTION_HISTORY_FRAMES = 5

AUDIO_ENERGY_PERCENTILE = 70
MIN_SILENCE_DURATION = 1.0
SPEECH_PAUSE_THRESHOLD = 0.5

CONTEXT_BEFORE_PEAK = 3.0

WHISPER_MODEL = "base"
WHISPER_LANGUAGE = None

SUBTITLE_FONT_SIZE = 70
SUBTITLE_FONT_COLOR = "yellow"
SUBTITLE_STROKE_COLOR = "black"
SUBTITLE_STROKE_WIDTH = 4
SUBTITLE_POSITION = ("center", "bottom")
SUBTITLE_BOTTOM_MARGIN = 150
SUBTITLE_MAX_CHARS_PER_LINE = 35
SUBTITLE_FONT = None
SUBTITLE_ANIMATION_ENABLED = True
SUBTITLE_ANIMATION_TYPE = "slide_up"
SUBTITLE_WORDS_PER_GROUP = 3

WEIGHT_MOTION = 0.3
WEIGHT_AUDIO_ENERGY = 0.3
WEIGHT_SPEECH_DENSITY = 0.2
WEIGHT_SCENE_CHANGES = 0.2

NUM_CLIPS = 5

CLIP_OVERLAP = 0.1

USE_MULTIPROCESSING = True
NUM_WORKERS = os.cpu_count() or 4
PARALLEL_CLIP_WORKERS = 3

LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

USE_BLURRED_BACKGROUND = True
BLUR_STRENGTH = 21
BACKGROUND_OPACITY = 0.7

MIN_SEGMENT_SCORE = 0.3

MAX_SEGMENTS_TO_ANALYZE = 100

USE_GPU = True

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(LOGS_DIR, exist_ok=True)
os.makedirs(TEMP_DIR, exist_ok=True)
